# Generated by Django 4.2.1 on 2026-07-12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0007_remove_test_spsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatagenSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.BigIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datagen_samples', to='OpenBench.test')),
            ],
            options={
                'indexes': [models.Index(fields=['test', 'created'], name='datagen_test_created_idx')],
            },
        ),
    ]
