# Generated by Django 4.2.1 on 2026-07-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0008_datagensample'),
        ('OpenBench', '0011_normalize_engine_source'),
    ]

    operations = []
